development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: mobile_zen_development
  pool: 5
  username: johncapecelatro  
  password:

test: &test
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: mobile_zen_test
  pool: 5
  username: johncapecelatro    
  password:

production:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: mobile_zen_production
  pool: 5
  username: johncapecelatro
  password:

cucumber:
  <<: *test